id: P26257F7D
initial_creation_type: input
source_metadata:
  title: Sakya Paṇḍita Series
  language: it
  description: 'A series of texts by and about the great scholar Sakya Paṇḍita Kunga
    Gyaltsen (kun dga'' rgyal mtshan, 1182–1251):'
  volume:
    7f4bf1b63dc04a318434f4b727b7c398:
      title: A Wondrous Instruction for the Moment of Death
      parent: Advice
    9e0bd90b89e249068c63f51b17996f5c:
      title: Meditation on Amitābha
      parent: Advice
    e6b3439567144641a784d3116d2b118c:
      title: Verses of Aspiration to Recite While Prostrating
      parent: Aspiration Prayers
    80da658ae1bb44d0aa4b2b7ffa6ee364:
      title: The Gaṇacakra Ritual
      parent: Commentaries
    382c7565322748279ca50aaf012e8058:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Guru Yoga
    997b6f72f8234acba66a2cca18beb5ac:
      title: 'The Sun of Ambrosial Wisdom: A Guru Yoga of Dharmarāja Sakya Paṇḍita'
      parent: Guru Yoga
    eb79972b911544ddb6ae6d6fe92139bd:
      title: Sakya Paṇḍita’s Instruction on Parting from the Four Attachments
      parent: Mind Training
    8a7a174a8d9a4f9b82d32cad74351db4:
      title: Praise to Sakya Paṇḍita
      parent: Praise
    0e042f7d48594d6596f9ca2a1c9b89e4:
      title: Prayer to Invoke the Wisdom Mind of the Gentle Protector Sakya Paṇḍita
      parent: Prayers
created_at: '2022-03-01T01:26:41.732211'
last_modified_at: '2022-03-01T01:26:41.732213'
